### PR TITLE
build js before pushing

### PR DESCRIPTION
**Pull request by andreyyyyyyyyy**

### CODE REVIEW

**Comment by Raynos** [comment]
I'd rather not add a dependency on `husky` ; I'd prefer to do git stuff myself.

**Comment by Raynos** [comment]
Right there's a module that does this. It's called `git-hooks-plus`

**Comment by heapwolf** [comment]
@andreyyyyyyyyy should this be closed?

**Comment by chicoxyzzy** [comment]
Closing this PR as stale. Fill free to leave comments here, so we can reconsider opening it

**Pull request closed without merging**
